#+TITLE: Network Extension for Basic Binary Packet
#+AUTHOR: Mark Cox

This extension to the basic binary packet library provides
applications with the ability to send packets over a network.

[TABLE-OF-CONTENTS]

* Installation
The prerequisites for this library are
- [[http://common-lisp.net/project/iolib/][~IOLIB~]]
- [[https://github.com/OdonataResearchLLC/lisp-unit][Lisp Unit]] (tests only)

The most current version of this library can be obtained from the git repository
#+begin_src sh
git clone <path>
#+end_src

Loading of this library can be achieved by evaluating
#+begin_src lisp
  (asdf:load-system "basic-binary-packet-network")
#+end_src

A number of tests accompany this extension to ensure it is working
correctly. These tests can be performed by evaluating
#+begin_src lisp
  (asdf:test-system "basic-binary-packet-network")
#+end_src

* Introduction
This library provides an interface for sending and receiving basic
binary packets over a network. This functionality is divided in to the
following components:
- Server :: Handle new basic binary packet connections.
- Client :: Establish a new connection to a basic binary packet
            server.
- Stream :: Manage a stream that can send and receive basic binary
            packets.

All of the above components use the asynchronous input and output
functionality provided by ~IOLIB~. The main effect of this choice is
that this library's design shares a number of similarities with
graphical user interface APIs where by callbacks are invoked from
within an event loop. To invoke the basic binary packet event loop
from your application you call the function ~PROCESS-EVENTS~.
#+begin_src lisp
(defun process-events (&key one-shot timeout &allow-other-keys))
#+end_src
The keyword argument ~ONE-SHOT~ specifies that only one invocation of
the event loop should occur. The keyword argument ~TIMEOUT~ specifies
that the event loop should continue to wait and process events until
no event has occurred within ~TIMEOUT~ milliseconds.

The ~PROCESS-EVENTS~ function simply invokes the function
~IOLIB:EVENT-DISPATCH~. More information on accessing the ~IOLIB~
state is described in the [[Advanced API]] section.

* Stream
The basic binary packet network stream protocol models the behavior of
a communication channel that can send and receive objects using the
basic binary packet protocol. An important characteristic of the
stream is that the order in which objects are received is the same as
the order they were written.

The function ~WRITE-OBJECT~ sends an ~OBJECT~ over the ~STREAM~. The
function ~FORCE-OUTPUT~ should be invoked after ~WRITE-OBJECT~ if
~OBJECT~ needs to be sent immediately.
#+begin_src lisp 
  (defgeneric write-object (stream object &key binary-type identifier &allow-other-keys))
#+end_src
The manner in which ~OBJECT~ is encoded is controlled by the
~BINARY-TYPE~ argument. The receiver of the sent packet will be able
to identify the packet using the 32-bit unsigned integer
~IDENTIFIER~. More information on the keyword arguments can be found
in the [[file:basic-binary-packet.org][basic binary packet documentation]].

It is an error if ~WRITE-OBJECT~ is called before the stream is in the
connected state. This can be determined directly using the function
~CONNECTEDP~.
#+begin_src lisp
  (defgeneric connectedp (stream))
#+end_src
An alternative method is to register an ~ON-CONNECTION~ callback
function.
#+begin_src lisp
  (defgeneric on-connection (stream))
  (defgeneric (setf on-connection) (function stream))
#+end_src
The callback function is invoked with a single object that is the
stream that has successfully connected to a server.

Objects decoded from stream data are obtained via the ~ON-OBJECT~
callback.
#+begin_src lisp  
  (defgeneric on-object (stream))
  (defgeneric (setf on-object) (function stream))
#+end_src
The assigned function must accept three arguments, the ~STREAM~ that
received the object, the ~OBJECT~ that was sent and the packet
~IDENTIFIER~ used to transmit the object.

When the stream is no longer required, the function ~CLOSE~ can be
used to release all operating system resources needed for network
communication.
#+begin_src lisp  
  (defgeneric close (stream &key abort &allow-other-keys))  
#+end_src

Any errors that have occurred on a stream object are communicated
using the ~ON-ERROR~ callback function.
#+begin_src lisp
  (defgeneric on-error (stream))
  (defgeneric (setf on-error) (function stream))
#+end_src
The ~ON-ERROR~ function must accept two arguments, the ~STREAM~ in
error and the ~ERROR~ condition. The stream is automatically closed
prior to invoking the ~ON-ERROR~ function.

An ~END-OF-FILE~ condition object is used to identify the event where
the communication channel is terminated by the other end of the
stream.

The complete list of conditions that can be communicated is defined by
the specific implementation of the stream protocol.

* Server
A basic binary packet network server listens for connections that use
the basic binary packet protocol. Starting a server is achieved by
using the ~MAKE-SERVER~ function.
#+begin_src lisp
  (defun make-server (address port on-new-connection &key reuse-address backlog))
#+end_src
The returned object represents an IPv4 network server that listens for
connections to the port number ~PORT~ on the host interface
~ADDRESS~. The ~ON-NEW-CONNECTION~ argument is a callback function
that will be invoked when the server accepts a new connection. Details
about the callback function will be explained shortly.  The ~ADDRESS~
argument is an ~IOLIB~ Internet address object and ~PORT~ is an
unsigned 16 bit integer. If the keyword argument ~REUSE-ADDRESS~ is
true, then ~MAKE-SERVER~ will not signal an error if the ~ADDRESS~ and
~PORT~ pair were recently used as a server on the current host. The
~BACKLOG~ argument represents the number of pending unaccepted
connections the operating system will hold available. Exceeding this
number results in any new connection being refused.

The object returned by ~MAKE-SERVER~ supports a number of functions
that permit interaction with the running server.

Notifications of new accepted connections are performed using the
~ON-NEW-CONNECTION~ callback function.
#+begin_src lisp  
  (defgeneric on-new-connection (server))
  (defgeneric (setf on-new-connection) (function server))
#+end_src
The callback function must accept two arguments, the ~SERVER~ object
that accepted the connection and a ~STREAM~ object that implements the
[[*Stream][stream]] protocol. Please be aware that the ~STREAM~ object will not be
in the connected state prior to calling the callback function. The
[[*Stream][stream]] documentation outlines when the stream is ready for
communication. Lastly, any operation involving the ~SERVER~ instance
only applies to the ~SERVER~ as the accepted connection is entirely
managed by the newly created ~STREAM~ object.

Terminating the server is achieved by calling the ~CLOSE~ function.
#+begin_src lisp
  (defgeneric close (server &key &allow-other-keys))
#+end_src

Notifications of any error involving the server specifically will be
communicated via the ~ON-ERROR~ callback.
#+begin_src lisp  
  (defgeneric on-error (server))
  (defgeneric (setf on-error) (value server))
#+end_src
The function ~CLOSE~ will be invoked on the server object prior to the
notification. The ~IOLIB~ documentation is unclear on what type of
errors a server socket will encounter at run time. I will update this
as more detailed information is obtained.

* Client
A basic binary packet client communicates to a server using the basic
binary packet protocol. Connecting to a remote server is performed
using the ~MAKE-CLIENT~ function.
#+begin_src lisp
(defun make-client (address port))
#+end_src
This function will return an object that is in the process of
connecting to a server listening on port number ~PORT~ at Internet
~ADDRESS~. The ~PORT~ argument must be an unsigned 16 bit number and
the ~ADDRESS~ argument is an ~IOLIB~ address object.

The returned object implements the [[*Stream][stream]] protocol in order to send
and receive objects.

* Advanced API
The advanced API provides access to two aspects of this extension, the
~IOLIB~ event base and expanding the types of stream sockets the
implementation can support.

** IOLIB
The objects returned by ~MAKE-SERVER~ and ~MAKE-CLIENT~ utilise the
asynchronous API provided by ~IOLIB~. Key to this API is the
~IOLIB:EVENT-BASE~ object. All objects created by in this library
share a single ~IOLIB:EVENT-BASE~ object. This object can be obtained
using the ~*EVENT-BASE*~ dynamic variable.

** Using sockets that are not IPV4.
I will write this section on request.
